export const api = {
  login: "/api/auth/login",
  register: "/api/auth/register",
  logout: "/api/auth/logout",
  session: "/api/session",
  forgotPassword: "/api/auth/forgot-password",
  resetPassword: "/api/auth/reset-password",
  confirmEmail: "/api/auth/confirm-email",
  profile: "/api/auth/profile",
  catalog: "/api/catalog",
  appointments: "/api/appointments",
  appointment: (id: string) => `/api/appointments/${encodeURIComponent(id)}`,
  appointmentAction: (id: string) => `/api/appointments/${encodeURIComponent(id)}/actions`,
  track: "/api/appointments/track",
  notifications: "/api/notifications",
  admin: "/api/admin",
  grievances: "/api/grievances",
} as const;
