export const routes = {
  home: "/",
  about: "/about",
  services: "/services",
  departments: "/departments",
  department: (id: string) => `/departments/${id}`,
  offices: "/offices",
  office: (id: string) => `/offices/${id}`,
  howItWorks: "/how-it-works",
  guidelines: "/guidelines",
  announcements: "/announcements",
  announcement: (id: string) => `/announcements/${id}`,
  citizenCharter: "/citizen-charter",
  faq: "/faq",
  accessibility: "/accessibility",
  help: "/help",
  contact: "/contact",
  grievance: "/grievance",
  track: "/track",
  login: "/login",
  register: "/register",
  bookAppointment: "/login?intent=book",
  citizenDashboard: "/citizen/dashboard",
  citizenAppointments: "/citizen/appointments",
  citizenAppointment: (id: string) => `/citizen/appointments/${id}`,
  citizenAppointmentTrack: (id: string) => `/citizen/appointments/${id}/track`,
  citizenAppointmentLetter: (id: string) => `/citizen/appointments/${id}/letter`,
  citizenAppointmentQr: (id: string) => `/citizen/appointments/${id}/qr`,
  publicTrack: (id?: string) => (id ? `/track?id=${encodeURIComponent(id)}` : "/track"),
  citizenBook: "/citizen/appointments/new",
  citizenProfile: "/citizen/profile",
  citizenNotifications: "/citizen/notifications",
  officialLogin: "/official/login",
  officialDashboard: "/official/dashboard",
  officialRequests: "/official/requests",
  officialRequest: (id: string) => `/official/requests/${id}`,
  officialTransfer: (id: string) => `/official/requests/${id}/transfer`,
  officialCalendar: "/official/calendar",
  officialAppointments: "/official/appointments",
  officialMeeting: (id: string) => `/official/meetings/${id}`,
  officialReports: "/official/reports",
  officialNotifications: "/official/notifications",
  officialProfile: "/official/profile",
  frontDeskLogin: "/front-desk/login",
  frontDeskDashboard: "/front-desk/dashboard",
  frontDeskSearch: "/front-desk/search",
  frontDeskVisit: (id: string) => `/front-desk/visits/${id}`,
  frontDeskQueue: "/front-desk/queue",
  frontDeskProfile: "/front-desk/profile",
  adminLogin: "/admin/login",
  adminDashboard: "/admin/dashboard",
  adminOffices: "/admin/offices",
  adminDepartments: "/admin/departments",
  adminCategories: "/admin/categories",
  adminOfficials: "/admin/officials",
  adminUsers: "/admin/users",
  adminRoles: "/admin/roles",
  adminAppointments: "/admin/appointments",
  adminSlots: "/admin/slots",
  adminHolidays: "/admin/holidays",
  adminSla: "/admin/sla",
  adminEscalation: "/admin/escalation",
  adminNotifications: "/admin/notifications",
  adminReports: "/admin/reports",
  adminAudit: "/admin/audit",
  adminSettings: "/admin/settings",
} as const;
